spring:
  profiles:
    active: dev # dev, test, prod
  main:
    allow-circular-references: true # 允许循环依赖
  datasource:
    druid:
      driver-class-name: ${traffic.datasource.driver-class-name}
      url: jdbc:mysql://${traffic.datasource.host}:${traffic.datasource.port}/${traffic.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${traffic.datasource.username}
      password: ${traffic.datasource.password}

logging:
  config: classpath:logback-spring.xml # 日志配置文件

mybatis:
    #mapper配置文件
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.entity
server:
  port: 8082